name: Deploy AMBA

on:
  workflow_dispatch: {}

permissions:
  id-token: write
  contents: read

env:
  Location: "westeurope"
  ManagementGroupPrefix: "225b122c-22cd-45b0-95c2-21ee5de01f0d" # pseudo root management group

jobs:
  deploy_job:
    runs-on: ubuntu-latest
    environment: main

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: "Login to Azure"
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true

      - name: Az CLI Deploy AMBA ARM template
        id: deploy_amba
        shell: bash
        run: |
          az deployment mg create --template-uri https://raw.githubusercontent.com/jagiraud/azure-monitor-baseline-alerts/main/patterns/alz/alzArm.json --location ${{ env.Location }} --management-group-id ${{ env.ManagementGroupPrefix }} --parameters ./patterns/alz/alzArm.param.json
